### ISSUE TITLE
test of automake fail

### ISSUE THREAD

**Issue by syyhao1994** [autotools-mirror/automake#2]
when i rebuild automake, there were three test fail,  list as below
FAIL: t/am-prog-cc-c-o.sh
FAIL: t/ccnoco.sh
FAIL: t/ccnoco-lib.sh
============================================================================
 Testsuite summary for GNU Automake 1.16.1
 ============================================================================
 # TOTAL: 2688
 # PASS:  2459
 # SKIP:  187
 # XFAIL: 39
 # FAIL:  3
 # XPASS: 0
 # ERROR: 0

how can i fix this problem?

**Comment by TimothyGu** [comment]
This is just a mirror of automake. Please don't file issues here.
