### ISSUE TITLE
rpath problems when using non-root rpmbuild 

### ISSUE THREAD

**Issue by windiana42** [autotools-mirror/automake#3]
I struggled to get my project built on opensuse build service which uses non-root rpmbuild and finally checks that no rpath is set in executables and shared libraries. (I can provide links to the project, but I probably should rather setup a minimal problem reproducing the case if needed)

The situation is that it is recommended to run configure with --libdir $BUILDROOT$libdir within the rpmbuild spec file. However, $BUILDROOT should not appear within rpath of executables and shared libraries.

I traced the problem to two actions of automake. 
1) `aclocal` sets `-rpath $wl$libdir` in `libtool` variable `hardcode_libdir_flag_spec` based on `configure --prefix` parameter
```bash
  if test yes = "$lt_use_gnu_ld_interface"; then
...
    _LT_TAGVAR(hardcode_libdir_flag_spec, $1)='$wl-rpath $wl$libdir'
```
2) `automake` writes `$(AM_V_CXXLD)$(CXXLINK) -rpath ${libdir}` in `Makefile.in` when generating shared libraries where `${libdir}` also includes `configure --prefix` parameter 

Would it be possible to implement a `--with-rpath` parameter for `aclocal` based `configure` scripts that makes rpath differ from `--prefix` based library path determination?

**Comment by TimothyGu** [comment]
This is just a mirror of automake. Please don't file issues here.
