### ISSUE TITLE
./configure: line 1986: syntax error near unexpected token `yes' ./configure: line 1986: `AM_SILENT_RULES(yes)'

### ISSUE THREAD

**Issue by forkbabu** [autotools-mirror/automake#5]
```
autoconf -f -i
```
```
./configure --prefix=$HOME/local
```
![image](https://user-images.githubusercontent.com/8037297/208182834-ac22c3c8-d1f5-4014-8f81-d4f62954a00e.png)

@kberry @zackw any solutions?

**Comment by zackw** [comment]
Gonna need to see your entire configure.ac to have a prayer of helping.
